lexicon = {

    # 
    "she": {"mr": "ती", "gender": "F", "number": "sg" , "person" : "tp"},
    "he": {"mr": "तो", "gender": "M", "number": "sg", "person" : "tp"} ,
    "apple": {"mr": "सफरचंद", "pos": "N"},
    "water": {"mr": "पाणी", "pos": "N"},


    # verbs
    "accept": {"root": "स्वीकारणे", "pos": "V", "tense": "present"},
    "add": {"root": "जोडणे", "pos": "V", "tense": "present"},
    "allow": {"root": "परवानगी देणे", "pos": "V", "tense": "present"},
    "ask": {"root": "विचारणे", "pos": "V", "tense": "present"},
    "be": {"root": "असणे", "pos": "V", "tense": "present"},
    "become": {"root": "होणे", "pos": "V", "tense": "present"},
    "begin": {"root": "सुरू करणे", "pos": "V", "tense": "present"},
    "break": {"root": "फोडणे", "pos": "V", "tense": "present"},
    "bring": {"root": "आणणे", "pos": "V", "tense": "present"},
    "build": {"root": "बांधणे", "pos": "V", "tense": "present"},
    "buy": {"root": "खरेदी करणे", "pos": "V", "tense": "present"},
    "call": {"root": "बोलावणे", "pos": "V", "tense": "present"},
    "can": {"root": "शकणे", "pos": "V", "tense": "present"},
    "change": {"root": "बदलणे", "pos": "V", "tense": "present"},
    "choose": {"root": "निवडणे", "pos": "V", "tense": "present"},
    "come": {"root": "येणे", "pos": "V", "tense": "present"},
    "cut": {"root": "कापणे", "pos": "V", "tense": "present"},
    "do": {"root": "करणे", "pos": "V", "tense": "present"},
    "draw": {"root": "काढणे", "pos": "V", "tense": "present"},
    "drink": {"root": "पिणे", "pos": "V", "tense": "present"},
    "drive": {"root": "चालवणे", "pos": "V", "tense": "present"},
    "eat": {"root": "खाणे", "pos": "V", "tense": "present"},
    "fall": {"root": "पडणे", "pos": "V", "tense": "present"},
    "feel": {"root": "वाटणे", "pos": "V", "tense": "present"},
    "find": {"root": "शोधणे", "pos": "V", "tense": "present"},
    "fly": {"root": "उडणे", "pos": "V", "tense": "present"},
    "forget": {"root": "विसरणे", "pos": "V", "tense": "present"},
    "get": {"root": "मिळवणे", "pos": "V", "tense": "present"},
    "give": {"root": "देणे", "pos": "V", "tense": "present"},
    "go": {"root": "जाणे", "pos": "V", "tense": "present"},
    "grow": {"root": "वाढणे", "pos": "V", "tense": "present"},
    "have": {"root": "असणे", "pos": "V", "tense": "present"},
    "hear": {"root": "ऐकणे", "pos": "V", "tense": "present"},
    "help": {"root": "मदत करणे", "pos": "V", "tense": "present"},
    "hold": {"root": "धरणे", "pos": "V", "tense": "present"},
    "keep": {"root": "ठेवणे", "pos": "V", "tense": "present"},
    "know": {"root": "माहित असणे", "pos": "V", "tense": "present"},
    "leave": {"root": "सोडणे", "pos": "V", "tense": "present"},
    "let": {"root": "देणे", "pos": "V", "tense": "present"},
    "like": {"root": "आवडणे", "pos": "V", "tense": "present"},
    "live": {"root": "राहणे", "pos": "V", "tense": "present"},
    "look": {"root": "पाहणे", "pos": "V", "tense": "present"},
    "make": {"root": "बनवणे", "pos": "V", "tense": "present"},
    "may": {"root": "शक्य असणे", "pos": "V", "tense": "present"},
    "mean": {"root": "अर्थ असणे", "pos": "V", "tense": "present"},
    "meet": {"root": "भेटणे", "pos": "V", "tense": "present"},
    "move": {"root": "हलवणे", "pos": "V", "tense": "present"},
    "need": {"root": "गरज असणे", "pos": "V", "tense": "present"},
    "open": {"root": "उघडणे", "pos": "V", "tense": "present"},
    "pay": {"root": "पैसे देणे", "pos": "V", "tense": "present"},
    "play": {"root": "खेळणे", "pos": "V", "tense": "present"},
    "put": {"root": "ठेवणे", "pos": "V", "tense": "present"},
    "read": {"root": "वाचणे", "pos": "V", "tense": "present"},
    "ride": {"root": "स्वार होणे", "pos": "V", "tense": "present"},
    "run": {"root": "धावणे", "pos": "V", "tense": "present"},
    "say": {"root": "सांगणे", "pos": "V", "tense": "present"},
    "see": {"root": "पाहणे", "pos": "V", "tense": "present"},
    "sell": {"root": "विकणे", "pos": "V", "tense": "present"},
    "send": {"root": "पाठवणे", "pos": "V", "tense": "present"},
    "set": {"root": "ठरवणे", "pos": "V", "tense": "present"},
    "show": {"root": "दाखवणे", "pos": "V", "tense": "present"},
    "shut": {"root": "बंद करणे", "pos": "V", "tense": "present"},
    "sing": {"root": "गाणे", "pos": "V", "tense": "present"},
    "sit": {"root": "बसणे", "pos": "V", "tense": "present"},
    "sleep": {"root": "झोपणे", "pos": "V", "tense": "present"},
    "speak": {"root": "बोलणे", "pos": "V", "tense": "present"},
    "spend": {"root": "खर्च करणे", "pos": "V", "tense": "present"},
    "stand": {"root": "उभे राहणे", "pos": "V", "tense": "present"},
    "start": {"root": "सुरू करणे", "pos": "V", "tense": "present"},
    "stop": {"root": "थांबवणे", "pos": "V", "tense": "present"},
    "study": {"root": "अभ्यास करणे", "pos": "V", "tense": "present"},
    "suggest": {"root": "सूचना देणे", "pos": "V", "tense": "present"},
    "support": {"root": "समर्थन करणे", "pos": "V", "tense": "present"},
    "swim": {"root": "पोहणे", "pos": "V", "tense": "present"},
    "take": {"root": "घेणे", "pos": "V", "tense": "present"},
    "talk": {"root": "बोलणे", "pos": "V", "tense": "present"},
    "teach": {"root": "शिकवणे", "pos": "V", "tense": "present"},
    "tell": {"root": "सांगणे", "pos": "V", "tense": "present"},
    "think": {"root": "विचार करणे", "pos": "V", "tense": "present"},
    "throw": {"root": "फेकणे", "pos": "V", "tense": "present"},
    "touch": {"root": "स्पर्श करणे", "pos": "V", "tense": "present"},
    "travel": {"root": "प्रवास करणे", "pos": "V", "tense": "present"},
    "try": {"root": "प्रयत्न करणे", "pos": "V", "tense": "present"},
    "turn": {"root": "वळणे", "pos": "V", "tense": "present"},
    "understand": {"root": "समजणे", "pos": "V", "tense": "present"},
    "use": {"root": "वापरणे", "pos": "V", "tense": "present"},
    "wait": {"root": "थांबणे", "pos": "V", "tense": "present"},
    "wake": {"root": "जागे होणे", "pos": "V", "tense": "present"},
    "walk": {"root": "चालणे", "pos": "V", "tense": "present"},
    "want": {"root": "इच्छित असणे", "pos": "V", "tense": "present"},
    "watch": {"root": "पाहणे", "pos": "V", "tense": "present"},
    "win": {"root": "जिंकणे", "pos": "V", "tense": "present"},
    "wish": {"root": "इच्छा करणे", "pos": "V", "tense": "present"},
    "work": {"root": "काम करणे", "pos": "V", "tense": "present"},
    "write": {"root": "लिहिणे", "pos": "V", "tense": "present"},
    "agree": {"root": "सहमत होणे", "pos": "V", "tense": "present"},
    "arrive": {"root": "पोहोचणे", "pos": "V", "tense": "present"},
    "believe": {"root": "विश्वास ठेवणे", "pos": "V", "tense": "present"},
    "carry": {"root": "नेणे", "pos": "V", "tense": "present"},
    "clean": {"root": "स्वच्छ करणे", "pos": "V", "tense": "present"} ,

    "admire": {"root": "प्रशंसा करणे", "pos": "V", "tense": "present"},
    "admit": {"root": "मान्य करणे", "pos": "V", "tense": "present"},
    "afford": {"root": "परवडणे", "pos": "V", "tense": "present"},
    "announce": {"root": "जाहिर करणे", "pos": "V", "tense": "present"},
    "answer": {"root": "उत्तर देणे", "pos": "V", "tense": "present"},
    "appear": {"root": "दिसणे", "pos": "V", "tense": "present"},
    "apply": {"root": "अर्ज करणे", "pos": "V", "tense": "present"},
    "argue": {"root": "वाद करणे", "pos": "V", "tense": "present"},
    "arrange": {"root": "आयोजन करणे", "pos": "V", "tense": "present"},
    "attack": {"root": "हल्ला करणे", "pos": "V", "tense": "present"},
    "avoid": {"root": "टाळणे", "pos": "V", "tense": "present"},
    "bake": {"root": "बेक करणे", "pos": "V", "tense": "present"},
    "behave": {"root": "वागणे", "pos": "V", "tense": "present"},
    "belong": {"root": "संबंधित असणे", "pos": "V", "tense": "present"},
    "blink": {"root": "पापणी लवणे", "pos": "V", "tense": "present"},
    "borrow": {"root": "उधार घेणे", "pos": "V", "tense": "present"},
    "breathe": {"root": "श्वास घेणे", "pos": "V", "tense": "present"},
    "burn": {"root": "जळणे", "pos": "V", "tense": "present"},
    "care": {"root": "काळजी घेणे", "pos": "V", "tense": "present"},
    "carry": {"root": "नेणे", "pos": "V", "tense": "present"},
    "catch": {"root": "पकडणे", "pos": "V", "tense": "present"},
    "cheat": {"root": "फसवणे", "pos": "V", "tense": "present"},
    "check": {"root": "तपासणे", "pos": "V", "tense": "present"},
    "climb": {"root": "चढणे", "pos": "V", "tense": "present"},
    "close": {"root": "बंद करणे", "pos": "V", "tense": "present"},
    "collect": {"root": "संग्रह करणे", "pos": "V", "tense": "present"},
    "compare": {"root": "तुलना करणे", "pos": "V", "tense": "present"},
    "complain": {"root": "तक्रार करणे", "pos": "V", "tense": "present"},
    "confuse": {"root": "गोंधळवणे", "pos": "V", "tense": "present"},
    "connect": {"root": "जोडणे", "pos": "V", "tense": "present"},
    "contain": {"root": "असणे", "pos": "V", "tense": "present"},
    "continue": {"root": "सुरू ठेवणे", "pos": "V", "tense": "present"},
    "cook": {"root": "शिजवणे", "pos": "V", "tense": "present"},
    "copy": {"root": "प्रत करणे", "pos": "V", "tense": "present"},
    "correct": {"root": "दुरुस्त करणे", "pos": "V", "tense": "present"},
    "count": {"root": "मोजणे", "pos": "V", "tense": "present"},
    "cover": {"root": "झाकणे", "pos": "V", "tense": "present"},
    "create": {"root": "निर्माण करणे", "pos": "V", "tense": "present"},
    "cross": {"root": "ओलांडणे", "pos": "V", "tense": "present"},
    "cry": {"root": "रडणे", "pos": "V", "tense": "present"},
    "dance": {"root": "नाचणे", "pos": "V", "tense": "present"},
    "decide": {"root": "निर्णय घेणे", "pos": "V", "tense": "present"},
    "deliver": {"root": "पुरवणे", "pos": "V", "tense": "present"},
    "depend": {"root": "आधार असणे", "pos": "V", "tense": "present"},
    "describe": {"root": "वर्णन करणे", "pos": "V", "tense": "present"},
    "design": {"root": "रचना करणे", "pos": "V", "tense": "present"},
    "destroy": {"root": "नष्ट करणे", "pos": "V", "tense": "present"},
    "develop": {"root": "विकसित करणे", "pos": "V", "tense": "present"},
    "discuss": {"root": "चर्चा करणे", "pos": "V", "tense": "present"},
    "divide": {"root": "विभाजित करणे", "pos": "V", "tense": "present"},
    "dress": {"root": "पोशाख घालणे", "pos": "V", "tense": "present"},
    "drop": {"root": "सोडणे", "pos": "V", "tense": "present"},
    "earn": {"root": "कमवणे", "pos": "V", "tense": "present"},
    "edit": {"root": "संपादित करणे", "pos": "V", "tense": "present"},
    "enable": {"root": "सक्षम करणे", "pos": "V", "tense": "present"},
    "encourage": {"root": "प्रोत्साहित करणे", "pos": "V", "tense": "present"},
    "enjoy": {"root": "आनंद घेणे", "pos": "V", "tense": "present"},
    "enter": {"root": "प्रवेश करणे", "pos": "V", "tense": "present"},
    "escape": {"root": "पळून जाणे", "pos": "V", "tense": "present"},
    "explain": {"root": "समजावून सांगणे", "pos": "V", "tense": "present"},
    "face": {"root": "सामोरे जाणे", "pos": "V", "tense": "present"},
    "fail": {"root": "अपयशी होणे", "pos": "V", "tense": "present"},
    "fill": {"root": "भरून काढणे", "pos": "V", "tense": "present"},
    "finish": {"root": "समाप्त करणे", "pos": "V", "tense": "present"},
    "fix": {"root": "दुरुस्त करणे", "pos": "V", "tense": "present"},
    "flow": {"root": "वाहणे", "pos": "V", "tense": "present"},
    "follow": {"root": "अनुसरण करणे", "pos": "V", "tense": "present"},
    "force": {"root": "बळजबरी करणे", "pos": "V", "tense": "present"},
    "form": {"root": "घडवणे", "pos": "V", "tense": "present"},
    "gain": {"root": "मिळवणे", "pos": "V", "tense": "present"},
    "guess": {"root": "अंदाज लावणे", "pos": "V", "tense": "present"},
    "handle": {"root": "हाताळणे", "pos": "V", "tense": "present"},
    "happen": {"root": "घडणे", "pos": "V", "tense": "present"},
    "hate": {"root": "द्वेष करणे", "pos": "V", "tense": "present"},
    "hide": {"root": "लपवणे", "pos": "V", "tense": "present"},
    "hope": {"root": "आशा करणे", "pos": "V", "tense": "present"},
    "identify": {"root": "ओळखणे", "pos": "V", "tense": "present"},
    "imagine": {"root": "कल्पना करणे", "pos": "V", "tense": "present"},
    "improve": {"root": "सुधारणा करणे", "pos": "V", "tense": "present"},
    "include": {"root": "समाविष्ट करणे", "pos": "V", "tense": "present"},
    "increase": {"root": "वाढवणे", "pos": "V", "tense": "present"},
    "inform": {"root": "माहिती देणे", "pos": "V", "tense": "present"},
    "insist": {"root": "आग्रह करणे", "pos": "V", "tense": "present"},
    "introduce": {"root": "ओळख करून देणे", "pos": "V", "tense": "present"},
    "invite": {"root": "आमंत्रित करणे", "pos": "V", "tense": "present"},
    "join": {"root": "सामील होणे", "pos": "V", "tense": "present"},
    "jump": {"root": "उडी मारणे", "pos": "V", "tense": "present"},
    "kill": {"root": "मारणे", "pos": "V", "tense": "present"},
    "laugh": {"root": "हसणे", "pos": "V", "tense": "present"},
    "learn": {"root": "शिकणे", "pos": "V", "tense": "present"},
    "lend": {"root": "उधार देणे", "pos": "V", "tense": "present"},
    "lie": {"root": "खोटे बोलणे", "pos": "V", "tense": "present"},
    "lift": {"root": "उचलणे", "pos": "V", "tense": "present"},
    "limit": {"root": "मर्यादा घालणे", "pos": "V", "tense": "present"},
    "listen": {"root": "ऐकणे", "pos": "V", "tense": "present"},
    "lose": {"root": "गमावणे", "pos": "V", "tense": "present"},
    "manage": {"root": "व्यवस्थापित करणे", "pos": "V", "tense": "present"},
    "mark": {"root": "खुण करणे", "pos": "V", "tense": "present"},
    "marry": {"root": "लग्न करणे", "pos": "V", "tense": "present"},
    "match": {"root": "जुळवणे", "pos": "V", "tense": "present"},
    "measure": {"root": "मोजणे", "pos": "V", "tense": "present"},
    "mention": {"root": "उल्लेख करणे", "pos": "V", "tense": "present"},
    "miss": {"root": "चुकवणे", "pos": "V", "tense": "present"},
    "mix": {"root": "मिश्रण करणे", "pos": "V", "tense": "present"},
    "notice": {"root": "लक्षात घेणे", "pos": "V", "tense": "present"},
    "offer": {"root": "ऑफर करणे", "pos": "V", "tense": "present"},
    "order": {"root": "आदेश देणे", "pos": "V", "tense": "present"},
    "own": {"root": "मालकी असणे", "pos": "V", "tense": "present"} ,

    "obtain": {"root": "प्राप्त करणे", "pos": "V", "tense": "present"},
    "occur": {"root": "घडणे", "pos": "V", "tense": "present"},
    "organize": {"root": "आयोजित करणे", "pos": "V", "tense": "present"},
    "overcome": {"root": "जिंकणे", "pos": "V", "tense": "present"},
    "own": {"root": "मालकी असणे", "pos": "V", "tense": "present"},
    "pack": {"root": "पॅक करणे", "pos": "V", "tense": "present"},
    "paint": {"root": "रंगवणे", "pos": "V", "tense": "present"},
    "participate": {"root": "सहभाग घेणे", "pos": "V", "tense": "present"},
    "pass": {"root": "पास होणे", "pos": "V", "tense": "present"},
    "perform": {"root": "सादर करणे", "pos": "V", "tense": "present"},
    "permit": {"root": "परवानगी देणे", "pos": "V", "tense": "present"},
    "pick": {"root": "उचलणे", "pos": "V", "tense": "present"},
    "plan": {"root": "योजना करणे", "pos": "V", "tense": "present"},
    "point": {"root": "दाखवणे", "pos": "V", "tense": "present"},
    "pour": {"root": "ओतणे", "pos": "V", "tense": "present"},
    "prefer": {"root": "प्राधान्य देणे", "pos": "V", "tense": "present"},
    "prepare": {"root": "तयार करणे", "pos": "V", "tense": "present"},
    "present": {"root": "सादर करणे", "pos": "V", "tense": "present"},
    "press": {"root": "दाबणे", "pos": "V", "tense": "present"},
    "prevent": {"root": "प्रतिबंध करणे", "pos": "V", "tense": "present"},
    "print": {"root": "छापणे", "pos": "V", "tense": "present"},
    "produce": {"root": "उत्पन्न करणे", "pos": "V", "tense": "present"},
    "promise": {"root": "वचन देणे", "pos": "V", "tense": "present"},
    "protect": {"root": "संरक्षण करणे", "pos": "V", "tense": "present"},
    "prove": {"root": "सिद्ध करणे", "pos": "V", "tense": "present"},
    "provide": {"root": "पुरवणे", "pos": "V", "tense": "present"},
    "publish": {"root": "प्रकाशित करणे", "pos": "V", "tense": "present"},
    "push": {"root": "ढकलणे", "pos": "V", "tense": "present"},
    "raise": {"root": "उचलणे", "pos": "V", "tense": "present"},
    "reach": {"root": "पोहोचणे", "pos": "V", "tense": "present"},
    "realize": {"root": "जाणीव होणे", "pos": "V", "tense": "present"},
    "receive": {"root": "स्वीकारणे", "pos": "V", "tense": "present"},
    "recognize": {"root": "ओळखणे", "pos": "V", "tense": "present"},
    "record": {"root": "नोंद करणे", "pos": "V", "tense": "present"},
    "reduce": {"root": "कमी करणे", "pos": "V", "tense": "present"},
    "reflect": {"root": "परावर्तित करणे", "pos": "V", "tense": "present"},
    "refuse": {"root": "नकार देणे", "pos": "V", "tense": "present"},
    "regret": {"root": "पश्चात्ताप करणे", "pos": "V", "tense": "present"},
    "relax": {"root": "विश्रांती घेणे", "pos": "V", "tense": "present"},
    "release": {"root": "मुक्त करणे", "pos": "V", "tense": "present"},
    "remain": {"root": "राहणे", "pos": "V", "tense": "present"},
    "remind": {"root": "आठवण करून देणे", "pos": "V", "tense": "present"},
    "remove": {"root": "काढून टाकणे", "pos": "V", "tense": "present"},
    "repair": {"root": "दुरुस्त करणे", "pos": "V", "tense": "present"},
    "repeat": {"root": "पुन्हा करणे", "pos": "V", "tense": "present"},
    "replace": {"root": "बदलणे", "pos": "V", "tense": "present"},
    "reply": {"root": "उत्तर देणे", "pos": "V", "tense": "present"},
    "report": {"root": "अहवाल देणे", "pos": "V", "tense": "present"},
    "request": {"root": "विनंती करणे", "pos": "V", "tense": "present"},
    "require": {"root": "गरज असणे", "pos": "V", "tense": "present"},
    "rescue": {"root": "बचाव करणे", "pos": "V", "tense": "present"},
    "retire": {"root": "निवृत्त होणे", "pos": "V", "tense": "present"},
    "return": {"root": "परत येणे", "pos": "V", "tense": "present"},
    "review": {"root": "पुनरावलोकन करणे", "pos": "V", "tense": "present"},
    "ring": {"root": "वाजवणे", "pos": "V", "tense": "present"},
    "roll": {"root": "गोल फिरवणे", "pos": "V", "tense": "present"},
    "save": {"root": "जतन करणे", "pos": "V", "tense": "present"},
    "satisfy": {"root": "समाधान करणे", "pos": "V", "tense": "present"},
    "scream": {"root": "ओरडणे", "pos": "V", "tense": "present"},
    "search": {"root": "शोधणे", "pos": "V", "tense": "present"},
    "select": {"root": "निवडणे", "pos": "V", "tense": "present"},
    "separate": {"root": "वेगळे करणे", "pos": "V", "tense": "present"},
    "serve": {"root": "सेवा करणे", "pos": "V", "tense": "present"},
    "shake": {"root": "हलवणे", "pos": "V", "tense": "present"},
    "share": {"root": "सामायिक करणे", "pos": "V", "tense": "present"},
    "shoot": {"root": "गोळी मारणे", "pos": "V", "tense": "present"},
    "sign": {"root": "स्वाक्षरी करणे", "pos": "V", "tense": "present"},
    "smell": {"root": "वास घेणे", "pos": "V", "tense": "present"},
    "smile": {"root": "हसणे", "pos": "V", "tense": "present"},
    "solve": {"root": "सोडवणे", "pos": "V", "tense": "present"},
    "sort": {"root": "वर्गीकरण करणे", "pos": "V", "tense": "present"},
    "sound": {"root": "आवाज येणे", "pos": "V", "tense": "present"},
    "state": {"root": "मांडणे", "pos": "V", "tense": "present"},
    "steal": {"root": "चोरी करणे", "pos": "V", "tense": "present"},
    "stick": {"root": "चिटकवणे", "pos": "V", "tense": "present"},
    "store": {"root": "साठवणे", "pos": "V", "tense": "present"},
    "strengthen": {"root": "बळकट करणे", "pos": "V", "tense": "present"},
    "stretch": {"root": "ताणणे", "pos": "V", "tense": "present"},
    "struggle": {"root": "संघर्ष करणे", "pos": "V", "tense": "present"},
    "submit": {"root": "सादर करणे", "pos": "V", "tense": "present"},
    "succeed": {"root": "यशस्वी होणे", "pos": "V", "tense": "present"},
    "suffer": {"root": "दु:ख सहन करणे", "pos": "V", "tense": "present"},
    "suggest": {"root": "सूचना देणे", "pos": "V", "tense": "present"},
    "supply": {"root": "पुरवठा करणे", "pos": "V", "tense": "present"},
    "suppose": {"root": "गृहित धरणे", "pos": "V", "tense": "present"},
    "surprise": {"root": "आश्चर्यचकित करणे", "pos": "V", "tense": "present"},
    "survive": {"root": "जगणे", "pos": "V", "tense": "present"},
    "suspect": {"root": "संशय घेणे", "pos": "V", "tense": "present"},
    "swear": {"root": "शपथ घेणे", "pos": "V", "tense": "present"},
    "switch": {"root": "बदलणे", "pos": "V", "tense": "present"},
    "taste": {"root": "चव घेणे", "pos": "V", "tense": "present"},
    "tear": {"root": "फाडणे", "pos": "V", "tense": "present"},
    "test": {"root": "चाचणी करणे", "pos": "V", "tense": "present"},
    "thank": {"root": "आभार मानणे", "pos": "V", "tense": "present"},
    "threaten": {"root": "धमकावणे", "pos": "V", "tense": "present"},
    "train": {"root": "प्रशिक्षण देणे", "pos": "V", "tense": "present"},
    "translate": {"root": "अनुवाद करणे", "pos": "V", "tense": "present"},
    "treat": {"root": "वागणूक देणे", "pos": "V", "tense": "present"},
    "trust": {"root": "विश्वास ठेवणे", "pos": "V", "tense": "present"},
    "try": {"root": "प्रयत्न करणे", "pos": "V", "tense": "present"},
    "turn": {"root": "वळणे", "pos": "V", "tense": "present"},
    "type": {"root": "टाइप करणे", "pos": "V", "tense": "present"},
    "undergo": {"root": "अनुभवणे", "pos": "V", "tense": "present"},
    "update": {"root": "सुधारित करणे", "pos": "V", "tense": "present"},
    "upgrade": {"root": "सुधारणा करणे", "pos": "V", "tense": "present"},
    "upload": {"root": "अपलोड करणे", "pos": "V", "tense": "present"},
    "urge": {"root": "आग्रह करणे", "pos": "V", "tense": "present"},
    "vary": {"root": "बदलणे", "pos": "V", "tense": "present"},
    "view": {"root": "पाहणे", "pos": "V", "tense": "present"},
    "visit": {"root": "भेट देणे", "pos": "V", "tense": "present"},
    "vote": {"root": "मतदान करणे", "pos": "V", "tense": "present"},
    "warn": {"root": "इशारा देणे", "pos": "V", "tense": "present"},
    "waste": {"root": "वाया घालवणे", "pos": "V", "tense": "present"},
    "weigh": {"root": "वजन करणे", "pos": "V", "tense": "present"},
    "whisper": {"root": "कानात बोलणे", "pos": "V", "tense": "present"},
    "wonder": {"root": "आश्चर्य वाटणे", "pos": "V", "tense": "present"},
    "worry": {"root": "काळजी करणे", "pos": "V", "tense": "present"},
    "yell": {"root": "ओरडणे", "pos": "V", "tense": "present"},
    "zoom": {"root": "झूम करणे", "pos": "V", "tense": "present"} ,

    "abandon": {"root": "त्यागणे", "pos": "V", "tense": "present"},
    "absorb": {"root": "शोषून घेणे", "pos": "V", "tense": "present"},
    "abuse": {"root": "दुरुपयोग करणे", "pos": "V", "tense": "present"},
    "accelerate": {"root": "वेग वाढवणे", "pos": "V", "tense": "present"},
    "accompany": {"root": "सोबत जाणे", "pos": "V", "tense": "present"},
    "accuse": {"root": "आरोप करणे", "pos": "V", "tense": "present"},
    "acknowledge": {"root": "मान्य करणे", "pos": "V", "tense": "present"},
    "adapt": {"root": "जुळवून घेणे", "pos": "V", "tense": "present"},
    "address": {"root": "संबोधित करणे", "pos": "V", "tense": "present"},
    "adjust": {"root": "समायोजित करणे", "pos": "V", "tense": "present"},
    "advance": {"root": "पुढे जाणे", "pos": "V", "tense": "present"},
    "advertise": {"root": "जाहिरात करणे", "pos": "V", "tense": "present"},
    "advise": {"root": "सल्ला देणे", "pos": "V", "tense": "present"},
    "allocate": {"root": "वाटप करणे", "pos": "V", "tense": "present"},
    "amuse": {"root": "मनोरंजन करणे", "pos": "V", "tense": "present"},
    "analyze": {"root": "विश्लेषण करणे", "pos": "V", "tense": "present"},
    "anticipate": {"root": "आशा करणे", "pos": "V", "tense": "present"},
    "apologize": {"root": "माफी मागणे", "pos": "V", "tense": "present"},
    "appeal": {"root": "विनंती करणे", "pos": "V", "tense": "present"},
    "appoint": {"root": "नियुक्त करणे", "pos": "V", "tense": "present"},
    "appreciate": {"root": "कदर करणे", "pos": "V", "tense": "present"},
    "approach": {"root": "जवळ जाणे", "pos": "V", "tense": "present"},
    "approve": {"root": "मंजूर करणे", "pos": "V", "tense": "present"},
    "argue": {"root": "वाद करणे", "pos": "V", "tense": "present"},
    "arise": {"root": "उद्भवणे", "pos": "V", "tense": "present"},
    "assemble": {"root": "एकत्र करणे", "pos": "V", "tense": "present"},
    "assess": {"root": "मूल्यांकन करणे", "pos": "V", "tense": "present"},
    "assign": {"root": "नेमणूक करणे", "pos": "V", "tense": "present"},
    "assist": {"root": "सहाय्य करणे", "pos": "V", "tense": "present"},
    "assume": {"root": "गृहित धरणे", "pos": "V", "tense": "present"},
    "assure": {"root": "आश्वासन देणे", "pos": "V", "tense": "present"},
    "attach": {"root": "जोडणे", "pos": "V", "tense": "present"},
    "attempt": {"root": "प्रयत्न करणे", "pos": "V", "tense": "present"},
    "attract": {"root": "आकर्षित करणे", "pos": "V", "tense": "present"},
    "authorize": {"root": "अधिकृत करणे", "pos": "V", "tense": "present"},
    "balance": {"root": "संतुलन साधणे", "pos": "V", "tense": "present"},
    "bang": {"root": "ठोकर देणे", "pos": "V", "tense": "present"},
    "bathe": {"root": "आंघोळ करणे", "pos": "V", "tense": "present"},
    "beg": {"root": "भीक मागणे", "pos": "V", "tense": "present"},
    "bet": {"root": "शर्त लावणे", "pos": "V", "tense": "present"},
    "bind": {"root": "बांधणे", "pos": "V", "tense": "present"},
    "bleed": {"root": "रक्त वाहणे", "pos": "V", "tense": "present"},
    "bless": {"root": "आशीर्वाद देणे", "pos": "V", "tense": "present"},
    "boil": {"root": "उकळणे", "pos": "V", "tense": "present"},
    "bounce": {"root": "उडी मारणे", "pos": "V", "tense": "present"},
    "bow": {"root": "नम्र होणे", "pos": "V", "tense": "present"},
    "brake": {"root": "ब्रेक लावणे", "pos": "V", "tense": "present"},
    "bruise": {"root": "जखम करणे", "pos": "V", "tense": "present"},
    "brush": {"root": "ब्रश करणे", "pos": "V", "tense": "present"},
    "bubble": {"root": "फुगवणे", "pos": "V", "tense": "present"},
    "bump": {"root": "ठोकर देणे", "pos": "V", "tense": "present"},
    "bury": {"root": "पुरणे", "pos": "V", "tense": "present"},
    "calculate": {"root": "गणना करणे", "pos": "V", "tense": "present"},
    "capture": {"root": "पकडणे", "pos": "V", "tense": "present"},
    "carve": {"root": "कोरणे", "pos": "V", "tense": "present"},
    "cause": {"root": "कारण बनणे", "pos": "V", "tense": "present"},
    "challenge": {"root": "आव्हान देणे", "pos": "V", "tense": "present"},
    "charge": {"root": "शुल्क आकारणे", "pos": "V", "tense": "present"},
    "chase": {"root": "पाठलाग करणे", "pos": "V", "tense": "present"},
    "chew": {"root": "चावणे", "pos": "V", "tense": "present"},
    "chop": {"root": "चिरणे", "pos": "V", "tense": "present"},
    "claim": {"root": "दावा करणे", "pos": "V", "tense": "present"},
    "coach": {"root": "प्रशिक्षण देणे", "pos": "V", "tense": "present"},
    "collapse": {"root": "कोसळणे", "pos": "V", "tense": "present"},
    "command": {"root": "आदेश देणे", "pos": "V", "tense": "present"},
    "communicate": {"root": "संपर्क साधणे", "pos": "V", "tense": "present"},
    "compete": {"root": "स्पर्धा करणे", "pos": "V", "tense": "present"},
    "compliment": {"root": "प्रशंसा करणे", "pos": "V", "tense": "present"},
    "compose": {"root": "रचना करणे", "pos": "V", "tense": "present"},
    "concentrate": {"root": "एकाग्रता करणे", "pos": "V", "tense": "present"},
    "confess": {"root": "स्वीकार करणे", "pos": "V", "tense": "present"},
    "confirm": {"root": "पुष्टी करणे", "pos": "V", "tense": "present"},
    "congratulate": {"root": "अभिनंदन करणे", "pos": "V", "tense": "present"},
    "connect": {"root": "जोडणे", "pos": "V", "tense": "present"},
    "conserve": {"root": "संरक्षण करणे", "pos": "V", "tense": "present"},
    "consist": {"root": "असणे", "pos": "V", "tense": "present"},
    "consult": {"root": "सल्ला घेणे", "pos": "V", "tense": "present"},
    "contain": {"root": "असणे", "pos": "V", "tense": "present"},
    "convince": {"root": "समजावणे", "pos": "V", "tense": "present"},
    "cook": {"root": "शिजवणे", "pos": "V", "tense": "present"},
    "crawl": {"root": "रांगणे", "pos": "V", "tense": "present"},
    "creep": {"root": "हळूच जाणे", "pos": "V", "tense": "present"},
    "criticize": {"root": "टीका करणे", "pos": "V", "tense": "present"},
    "crush": {"root": "चिरडणे", "pos": "V", "tense": "present"},
    "cure": {"root": "उपचार करणे", "pos": "V", "tense": "present"},
    "curve": {"root": "वाकवणे", "pos": "V", "tense": "present"},
    "damage": {"root": "नुकसान करणे", "pos": "V", "tense": "present"},
    "dare": {"root": "धाडस करणे", "pos": "V", "tense": "present"},
    "deal": {"root": "व्यवहार करणे", "pos": "V", "tense": "present"},
    "debate": {"root": "चर्चा करणे", "pos": "V", "tense": "present"},
    "declare": {"root": "घोषणा करणे", "pos": "V", "tense": "present"},
    "decorate": {"root": "सजवणे", "pos": "V", "tense": "present"},
    "delay": {"root": "उशीर करणे", "pos": "V", "tense": "present"},
    "deliver": {"root": "पुरवणे", "pos": "V", "tense": "present"},
    "deny": {"root": "नकार देणे", "pos": "V", "tense": "present"},
    "depend": {"root": "आधार असणे", "pos": "V", "tense": "present"},
    "describe": {"root": "वर्णन करणे", "pos": "V", "tense": "present"},
    "deserve": {"root": "पात्र असणे", "pos": "V", "tense": "present"},
    "destroy": {"root": "नष्ट करणे", "pos": "V", "tense": "present"},
    "detect": {"root": "शोधणे", "pos": "V", "tense": "present"},
    "determine": {"root": "निर्धारित करणे", "pos": "V", "tense": "present"},
    "develop": {"root": "विकसित करणे", "pos": "V", "tense": "present"},
    "devote": {"root": "समर्पित करणे", "pos": "V", "tense": "present"},
    "differ": {"root": "वेगळे असणे", "pos": "V", "tense": "present"},
    "dig": {"root": "खोदणे", "pos": "V", "tense": "present"},
    "direct": {"root": "दिशा देणे", "pos": "V", "tense": "present"},
    "disagree": {"root": "असहमत असणे", "pos": "V", "tense": "present"},
    "disappear": {"root": "अदृश्य होणे", "pos": "V", "tense": "present"},
    "discover": {"root": "शोधून काढणे", "pos": "V", "tense": "present"} ,

    "discuss": {"root": "चर्चा करणे", "pos": "V", "tense": "present"},
    "dislike": {"root": "नापसंत करणे", "pos": "V", "tense": "present"},
    "dismiss": {"root": "काढून टाकणे", "pos": "V", "tense": "present"},
    "display": {"root": "प्रदर्शन करणे", "pos": "V", "tense": "present"},
    "disturb": {"root": "त्रास देणे", "pos": "V", "tense": "present"},
    "divide": {"root": "विभाजित करणे", "pos": "V", "tense": "present"},
    "drag": {"root": "ओढणे", "pos": "V", "tense": "present"},
    "dream": {"root": "स्वप्न पाहणे", "pos": "V", "tense": "present"},
    "dress": {"root": "पोशाख घालणे", "pos": "V", "tense": "present"},
    "drip": {"root": "ठिबकणे", "pos": "V", "tense": "present"},
    "educate": {"root": "शिक्षण देणे", "pos": "V", "tense": "present"},
    "eliminate": {"root": "काढून टाकणे", "pos": "V", "tense": "present"},
    "emphasize": {"root": "भर देणे", "pos": "V", "tense": "present"},
    "enable": {"root": "सक्षम करणे", "pos": "V", "tense": "present"},
    "encounter": {"root": "सामोरे जाणे", "pos": "V", "tense": "present"},
    "enforce": {"root": "अमलात आणणे", "pos": "V", "tense": "present"},
    "enhance": {"root": "वाढवणे", "pos": "V", "tense": "present"},
    "enroll": {"root": "नोंदणी करणे", "pos": "V", "tense": "present"},
    "ensure": {"root": "निश्चित करणे", "pos": "V", "tense": "present"},
    "entertain": {"root": "मनोरंजन करणे", "pos": "V", "tense": "present"},
    "escape": {"root": "पळून जाणे", "pos": "V", "tense": "present"},
    "estimate": {"root": "अंदाज करणे", "pos": "V", "tense": "present"},
    "evaluate": {"root": "मूल्यांकन करणे", "pos": "V", "tense": "present"},
    "examine": {"root": "चाचणी करणे", "pos": "V", "tense": "present"},
    "excite": {"root": "उत्तेजित करणे", "pos": "V", "tense": "present"},
    "exclude": {"root": "वगळणे", "pos": "V", "tense": "present"},
    "expand": {"root": "वाढवणे", "pos": "V", "tense": "present"},
    "expect": {"root": "अपेक्षा करणे", "pos": "V", "tense": "present"},
    "explode": {"root": "स्फोट होणे", "pos": "V", "tense": "present"},
    "explore": {"root": "अन्वेषण करणे", "pos": "V", "tense": "present"},
    "express": {"root": "व्यक्त करणे", "pos": "V", "tense": "present"},
    "extend": {"root": "वाढवणे", "pos": "V", "tense": "present"},
    "face": {"root": "सामोरे जाणे", "pos": "V", "tense": "present"},
    "fade": {"root": "फिकट होणे", "pos": "V", "tense": "present"},
    "fail": {"root": "अपयशी होणे", "pos": "V", "tense": "present"},
    "fancy": {"root": "आवडणे", "pos": "V", "tense": "present"},
    "fasten": {"root": "घट्ट करणे", "pos": "V", "tense": "present"},
    "feed": {"root": "खाऊ घालणे", "pos": "V", "tense": "present"},
    "fetch": {"root": "आणणे", "pos": "V", "tense": "present"},
    "file": {"root": "फाईल करणे", "pos": "V", "tense": "present"},
    "film": {"root": "चित्रपट काढणे", "pos": "V", "tense": "present"},
    "fire": {"root": "गोळीबार करणे", "pos": "V", "tense": "present"},
    "fit": {"root": "बसणे", "pos": "V", "tense": "present"},
    "float": {"root": "पाण्यावर तरंगणे", "pos": "V", "tense": "present"},
    "fold": {"root": "दुमडणे", "pos": "V", "tense": "present"},
    "forbid": {"root": "मनाई करणे", "pos": "V", "tense": "present"},
    "forecast": {"root": "भविष्यवाणी करणे", "pos": "V", "tense": "present"},
    "forgive": {"root": "माफ करणे", "pos": "V", "tense": "present"},
    "formulate": {"root": "रचना करणे", "pos": "V", "tense": "present"},
    "found": {"root": "स्थापन करणे", "pos": "V", "tense": "present"},
    "freeze": {"root": "गोठवणे", "pos": "V", "tense": "present"},
    "frighten": {"root": "घाबरवणे", "pos": "V", "tense": "present"},
    "gather": {"root": "एकत्र करणे", "pos": "V", "tense": "present"},
    "glow": {"root": "तेजस्वी होणे", "pos": "V", "tense": "present"},
    "govern": {"root": "शासन करणे", "pos": "V", "tense": "present"},
    "grin": {"root": "हसणे", "pos": "V", "tense": "present"},
    "guarantee": {"root": "हमी देणे", "pos": "V", "tense": "present"},
    "guard": {"root": "रक्षण करणे", "pos": "V", "tense": "present"},
    "guess": {"root": "अंदाज लावणे", "pos": "V", "tense": "present"},
    "handle": {"root": "हाताळणे", "pos": "V", "tense": "present"},
    "harass": {"root": "छळ करणे", "pos": "V", "tense": "present"},
    "harm": {"root": "इजा करणे", "pos": "V", "tense": "present"},
    "hesitate": {"root": "संकोच करणे", "pos": "V", "tense": "present"},
    "highlight": {"root": "ठळक करणे", "pos": "V", "tense": "present"},
    "hire": {"root": "भाड्याने घेणे", "pos": "V", "tense": "present"},
    "hop": {"root": "उडी मारणे", "pos": "V", "tense": "present"},
    "hug": {"root": "आलिंगन देणे", "pos": "V", "tense": "present"},
    "hum": {"root": "गाणे गुणगुणणे", "pos": "V", "tense": "present"},
    "hunt": {"root": "शिकार करणे", "pos": "V", "tense": "present"},
    "hurry": {"root": "घाई करणे", "pos": "V", "tense": "present"},
    "identify": {"root": "ओळखणे", "pos": "V", "tense": "present"},
    "ignore": {"root": "दुर्लक्ष करणे", "pos": "V", "tense": "present"},
    "illustrate": {"root": "चित्रित करणे", "pos": "V", "tense": "present"},
    "impress": {"root": "प्रभावित करणे", "pos": "V", "tense": "present"},
    "include": {"root": "समाविष्ट करणे", "pos": "V", "tense": "present"},
    "indicate": {"root": "सूचित करणे", "pos": "V", "tense": "present"},
    "inform": {"root": "माहिती देणे", "pos": "V", "tense": "present"},
    "inherit": {"root": "वारसा मिळवणे", "pos": "V", "tense": "present"},
    "instruct": {"root": "सूचना देणे", "pos": "V", "tense": "present"},
    "intend": {"root": "उद्दिष्ट असणे", "pos": "V", "tense": "present"},
    "interfere": {"root": "हस्तक्षेप करणे", "pos": "V", "tense": "present"},
    "interrupt": {"root": "मध्यमध्ये बोलणे", "pos": "V", "tense": "present"},
    "introduce": {"root": "ओळख करून देणे", "pos": "V", "tense": "present"},
    "invest": {"root": "गुंतवणूक करणे", "pos": "V", "tense": "present"},
    "invite": {"root": "आमंत्रित करणे", "pos": "V", "tense": "present"},
    "involve": {"root": "सामील करणे", "pos": "V", "tense": "present"},
    "iron": {"root": "इस्त्री करणे", "pos": "V", "tense": "present"},
    "irritate": {"root": "त्रास देणे", "pos": "V", "tense": "present"},
    "jog": {"root": "हळू धावणे", "pos": "V", "tense": "present"},
    "join": {"root": "सामील होणे", "pos": "V", "tense": "present"},
    "judge": {"root": "निर्णय करणे", "pos": "V", "tense": "present"},
    "justify": {"root": "न्याय देणे", "pos": "V", "tense": "present"}
}

